leson_1 spider keyword search
ksilex/gosearch pull request #1
Opened 2022-03-26 22:49 UTC by ksilex

2022-03-27 12:27 UTC, DmitriyVTitov requested changes
Ошибки необходимо обрабатывать. Пускай даже в виде простого вывода текста в выходной поток.

2022-03-27 12:27 UTC, DmitriyVTitov commented on cmd/main.go
> +package main
исполняемый пакет следует размещать в собственном каталоге внутри каталога `cmd`

2022-03-27 12:27 UTC, DmitriyVTitov commented on cmd/main.go
> +	search := flag.String("s", "", "search for keyword")
очень важно проверять ошибки, игнорировать их можно только в крайне редких случаях
https://github.com/hardcode-dev/go-core-3/blob/master/doc/%D0%A2%D0%B8%D0%BF%D0%BE%D0%B2%D1%8B%D0%B5%20%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B8.MD

2022-03-27 12:27 UTC, DmitriyVTitov commented on cmd/main.go
> +		i, _ := s.Scan(url, lvl)
полное игнорирование ошибок не допустимо
эта функций в принципе не может вернуть ошибку, зачем она тогда указана в сигнатуре?

2022-03-28 10:41 UTC, DmitriyVTitov approved these changes
Смотрите замечания.

2022-03-28 10:41 UTC, DmitriyVTitov commented on cmd/search/main.go
> +
избегайте таких пустых строк, тут можно потом случайно что-то вписать перед обработкой ошибки

2022-03-28 10:41 UTC, DmitriyVTitov commented on cmd/search/main.go
> +	for _, url := range urls[1:] {
`urls[1:]`?
то есть первый сайт пропускаем? но зачем?

2022-03-28 10:41 UTC, DmitriyVTitov commented on cmd/search/main.go
> +	res := make([]crawler.Document, 0)
если переменная не инициализируется конкретным значением, то лучше использовать `var`

2022-03-28 10:41 UTC, DmitriyVTitov commented on cmd/search/main.go
> +}
функция должна вернуть значение, а не печатать его
что, если я не хочу печатать? написать ещё одну функцию?
`searchDocs` - искать, а не печатать

2022-03-28 10:49 UTC, ksilex commented on cmd/search/main.go
> +	for _, url := range urls[1:] {
первый записывался в вызове #Scan в переменную "res", так показалось интереснее, чем просто инициализировать пустой массив

2022-03-30 17:48 UTC, merged